services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    privileged: true
    volumes:
      - ./config:/app/config
  plextraktsyncwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsyncwatch
    privileged: true
    # command: watch
    volumes:
      - ./config:/app/config
